# Categorical Data: Unique Values, Membership, Dummies

In [1]:
import pandas as pd 
ser = pd.Series({'AAPL':'Tech','XOM':'Energy','MSFT':'Tech','LULU':'Consumer','TSLA':'Consumer','GS':'Financials',
                'BAC':'Financials'})
ser

AAPL          Tech
XOM         Energy
MSFT          Tech
LULU      Consumer
TSLA      Consumer
GS      Financials
BAC     Financials
dtype: object

In [2]:
# Get Unique values
ser.unique()

array(['Tech', 'Energy', 'Consumer', 'Financials'], dtype=object)

In [3]:
# Get Unique Values & Counts
ser.value_counts()

Tech          2
Consumer      2
Financials    2
Energy        1
Name: count, dtype: int64

In [4]:
mask=ser.isin(['Financials','Tech'])
mask

AAPL     True
XOM     False
MSFT     True
LULU    False
TSLA    False
GS       True
BAC      True
dtype: bool

In [5]:
ser[mask]

AAPL          Tech
MSFT          Tech
GS      Financials
BAC     Financials
dtype: object

In [6]:
pd.get_dummies(ser)

      Consumer  Energy  Financials   Tech
AAPL     False   False       False   True
XOM      False    True       False  False
MSFT     False   False       False   True
LULU      True   False       False  False
TSLA      True   False       False  False
GS       False   False        True  False
BAC      False   False        True  False

In [8]:
# if the mask needs numeric indicators, add dtype=int

pd.get_dummies(ser, dtype=int)

      Consumer  Energy  Financials  Tech
AAPL         0       0           0     1
XOM          0       1           0     0
MSFT         0       0           0     1
LULU         1       0           0     0
TSLA         1       0           0     0
GS           0       0           1     0
BAC          0       0           1     0